version: "3.9"

# docker-compose -f docker-compose.dev.yml build
# docker-compose -f docker-compose.dev.yml up -d

services:

  react-portfolio:
    container_name: react-portfolio
    stdin_open: true
    restart: always
    build: .
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"